autoload -U colors && colors                                                    
PS1="%B%{$fg[green]%}%n%{$reset_color%}@%B%{$fg[green]%}%m %{$fg[yellow]%}%(5~|%-1~/.../%3~|%4~) %{$reset_color%}%% "
                                                                                
export CLICOLOR=1                                                               
export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd                                          
alias ll="ls -alG"                                                              

